target 'iosApp' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'shared', :path => '../shared'

  pod 'FirebaseAnalytics', '10.23.0'
  pod 'FirebaseCrashlytics', '10.23.0'
  
  pod 'KMPNativeCoroutinesAsync', '~> 1.0.0'
  pod 'KMPNativeCoroutinesCore', '~> 1.0.0'
end
